#include <algorithm>
#include <cmath>
#include <functional>
#include <vector>
#include <Cea/Core>

// Kolmogorov-Smirnov test.
// Tests whether data generated by a provided 
// cea::rvar is likely to have come from a
// distribution whose CDF is provided.
class ks_test
{
    public:
        ks_test(cea::rvar<double> * g, std::function<double(double)> f,
            int np) :
            gen(g), cdf(f), n_points(np) { }

        // Returns number of tests passed out of n
        // at significance level alpha.
        int n_tests(int n, double alpha);

        // Returns significance level required for
        // the generated data's KS statistic to cause
        // rejection of H0, namely "the data is drawn
        // from the provided distribution".
        double single_test();

    private:
        cea::rvar<double> * gen;
        std::function<double(double)> cdf;
        int n_points;
        std::vector<double> data;

        inline double square(double x) { return x*x; }

        void gen_data();
        double ks_cdf(double z);
};
