#!/bin/bash
current=$PWD
repo_root="$HOME/eng/cea"
tracked_hook="$repo_root/hooks/pre-commit"
execd_hook="$repo_root/.git/hooks/pre-commit"

# Failure handling function
fail()
{
	echo "Quitting without commit."
	exit 1
}

# First check diff between hook in .githooks and that in $GIT_DIR/hooks.
# If different update and abort with message.
if [ $tracked_hook -nt $execd_hook ]; then
	cp --backup $tracked_hook $execd_hook
	echo "Hook was out-of-date. Re-run 'git commit' to use new hook."
	fail
fi

# Next run gentests.py to produce test binary.
python "$repo_root/gentests.py" "$repo_root/tests/"
if [ $? -ne 0 ]; then
	echo "gentests.py failed."
	fail
fi

# Next is make
cmake --build "$repo_root"
if [ $? -ne 0 ]; then
	echo "Cmake failed."
	fail
fi

# Run test binary
$repo_root/tests/all
if [ $? -ne 0 ]; then
	echo "Test suite failed."
	fail
fi

echo "Proceeding to commit message."
sleep 1.5
exit 0
